### PR TITLE
merge two similar repositories

### PR DESCRIPTION
**Pull request by hardfire**
I merged the two lists as per our discussion [here](https://github.com/developers-nepal/tech-communities/issues/4#issuecomment-278693262) .
I think its fine, but i'm also having second thoughts. Does someone have any issues in merging these two, thus i created a PR. @techgaun @studenton

### CODE REVIEW

**Comment by techgaun** [comment]
lgtm. I don't have strong opinion but what do you think of separating into two section: github org / community group ?

**Comment by hardfire** [comment]
within the same list you mean right? 
and github orgs would exclude the communities (that could also have a github org)

**Comment by techgaun** [comment]
when a group has its associated github (and slack and whatever) we could link to the github repo..

```
### Groups

- [Developers Nepal](link_to_fb_group_here) - [Github](github_url) , [Slack](slack_url_here)

### Other groups

[Name of group](relevant_url)
```
what do you think

**Comment by hardfire** [comment]
okay :D I'll divide them as communities and groups.

**Comment by techgaun** [comment]
awesome sounds good @hardfire

**Review by amitness — COMMENTED** [review]
I agree with @techgaun. Separating them into two sections will be the best way to go.

**Comment by hardfire** [comment]
ok, check now, and one of you can merge it :D

**Review by techgaun — APPROVED** [review]

**Comment by hardfire** [comment]
thanks! i deleted the other repository.

**Pull request merged**
